name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: make
      run: make      
    name: Archive code coverage results
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/upload-artifact@v3.1.2
        with:
          name: linux-x86_64
          path: ./bfcomp
